repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        types: [file, python]

      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [file, python]

      - id: isort
        name: isort
        entry: isort
        language: python
        types: [file, python]
